### ISSUE TITLE
Issue with live video recording for android devices . 

### ISSUE THREAD

**Issue by samagarw** [sudharsan-selvaraj/appium-dashboard-plugin#111]
We are not able to see the live video for android devices while it is working fine for ios devices . 

It keeps on showing Loading live video ... and then doesn't load until the session finishes gracefully . 
<img width="992" alt="Screenshot 2023-01-11 at 5 29 00 PM" src="https://user-images.githubusercontent.com/5329851/211800895-6a64a470-d12b-469b-af48-979e03e04105.png">

**Comment by samagarw** [comment]
@sudharsan-selvaraj  : Any update on this ? I am getting live video for IOS devices but not for android . Should i pass any capability for this or enable any setting in android devices ?

**Comment by sudharsan-selvaraj** [comment]
@samagarw is it happening for all the android devices or only for specific device?

**Comment by samagarw** [comment]
@sudharsan-selvaraj  : Its happening for all the devices . We have added 5 devices and all are having this problem

**Comment by sudharsan-selvaraj** [comment]
@samagarw Can you check if `mjpegServerPort` capability is present in the session and try accessing the url directly from the browser and check if the video is loading. In the below image, the url will be `http://localhost:59567`

![image](https://user-images.githubusercontent.com/20136913/213615515-834add7d-37f5-4e05-b66d-23398c338bd6.png)

**Comment by samagarw** [comment]
@sudharsan-selvaraj  : I checked but it keeps on loading in browsertoo . 

Attaching screenshot 
1. Attached 1 for the mjpegserver port 
2. Attached 2 for the browser access . 

<img width="391" alt="Screenshot 2023-01-20 at 11 00 53 AM" src="https://user-images.githubusercontent.com/5329851/213624414-3bd2ca2e-e086-4408-923a-c68f65c187e3.png">
<img width="470" alt="Screenshot 2023-01-20 at 11 01 00 AM" src="https://user-images.githubusercontent.com/5329851/213624424-29b8c491-f21b-483e-af44-ccd003574b62.png">

**Comment by samagarw** [comment]
@sudharsan-selvaraj  : I tried with single thread . It is still not working .

**Comment by sudharsan-selvaraj** [comment]
@samagarw We have fixed it in the latest release. can you check if the issue got resolved?

**Comment by win5923** [comment]
@sudharsan-selvaraj still not working on real Android device. The URL is also loading endlessly.

**Comment by samagarw** [comment]
@sudharsan-selvaraj  : I am getting attached snapshot error  for android live 
<img width="595" alt="Screenshot 2023-06-14 at 11 40 37 PM" src="https://github.com/sudharsan-selvaraj/appium-dashboard-plugin/assets/5329851/1ea6bca7-d7a3-4050-b27a-4e6576648f95">

Can you please help here ?  .

**Comment by sudharsan-selvaraj** [comment]
@samagarw For live video streaming we rely on appium's mjpegServer. Few other android users also facing the same issue and it's already reported to appium https://github.com/appium/appium/issues/18325

I will also look out for any other possible fixes.

**Comment by win5923** [comment]
Using Docker to build Appium Server, this situation is unavoidable, right?

**Comment by krishtoautomate** [comment]
looks like it is os version related issues

**Comment by krishtoautomate** [comment]
video is recorded but live or replay is not working. im able to see video after download

**Comment by SushanthNandan** [comment]
@sudharsan-selvaraj Any update here, am using 2.0.3 and still live video is not coming for all the android devices

**Comment by DLavigneGH** [comment]
I also see the same issue, also on iOS, using real devices. Video is only available when the session closes.
I am on device-farm 8.4.7-rc10 and dashboard plugin 2.0.3, the latest to this date.

**Comment by SushanthN22** [comment]
@sudharsan-selvaraj Can you please help here

**Comment by sudharsan-selvaraj** [comment]
@samagarw As stated above (https://github.com/sudharsan-selvaraj/appium-dashboard-plugin/issues/111#issuecomment-1593498403), we don't have much control on how live video is generated as we are dependent on appium-uiautomator2-server.
