### ISSUE TITLE
Session stays running even after Appium Server Shut Down and restart of system

### ISSUE THREAD

**Issue by iepoch** [sudharsan-selvaraj/appium-dashboard-plugin#56]
The Session keeps running even after a reboot/restart of the system and when I run appium with the plugin it restarts these sessions. But with no way to stop them. I have clicked the Pause and checked they did not stop. I tried killing any other connections along with pids and I can't find anything related. Not sure if it's a bug or if someone can tell me how to shut them down so I can delete the runs. 
![image](https://user-images.githubusercontent.com/7504929/160702748-bd8e44f0-b67a-4159-a595-03141aa235fc.png)

**Comment by sudharsan-selvaraj** [comment]
@iepoch Thanks for reporting the issue. This is valid a bug from the plugin and it is fixed as part of https://github.com/sudharsan-selvaraj/appium-dashboard-plugin/pull/52

I will merge the PR and make a new release tomorrow that will solve the problem.

**Comment by sudharsan-selvaraj** [comment]
@iepoch Fix is now available in `v1.0.0-beta.12`. You can update the plugin using `appium plugin update appium-dashboard` command. Can you verify and close the issue if it's working as expected.

**Comment by iepoch** [comment]
I did try it this morning however I still have a issue it cleared the stack of sessions. However on 1 test run it kicked up 2 sessions one closed the other did not. 
![image](https://user-images.githubusercontent.com/7504929/160827045-0e24819f-6cb5-4759-ab9a-7a900d48c0da.png)

**Comment by sudharsan-selvaraj** [comment]
@iepoch Are you killing the web driver session at the end of each test execution? If the webdriver session is not killed, then appium server thinks that the session id is still active. That's the reason why you are seeing a spinner in the UI.
